"""Regenerate `docs/hash-chain.md` from `output/experiment_provenance.json`.

The human-readable hash-chain document is rendered from a Jinja-style
string template populated with the canonical machine-readable record
produced by `gen_provenance.py`. This separation guarantees that the
two artifacts are never out of sync — the JSON is the source of truth,
the Markdown is a derived view.

Usage:
    # 1. Refresh the JSON (must run after any source-file change).
    python scripts/gen_provenance.py
    # 2. Render the Markdown view from the refreshed JSON.
    python scripts/regen_hash_chain.py

Outputs:
    docs/hash-chain.md (overwritten in place).

Exit codes: 0 on success; 1 if `output/experiment_provenance.json` is missing.
"""

from __future__ import annotations

__author__ = "Carlos Ulisses Flores"
__email__ = "c.ulisses@gmail.com"
__orcid__ = "0000-0002-6034-7765"
__license__ = "Apache-2.0"

import json
import sys
from pathlib import Path
from string import Template

_ROOT = Path(__file__).resolve().parent.parent
_PROVENANCE = _ROOT / "output" / "experiment_provenance.json"
_OUTPUT = _ROOT / "docs" / "hash-chain.md"


_TEMPLATE = Template(r"""<!--
This file is regenerated by scripts/regen_hash_chain.py from output/experiment_provenance.json.
Manual edits will be overwritten on the next regeneration.
Source-of-truth for hashes: output/experiment_provenance.json (machine-readable).
-->

# Cryptographic Integrity Chain

> [!IMPORTANT]
> Single source of truth for the SHA-256 audit trail of this software artifact.
> Mathematical reproducibility is mechanically verifiable: given the pinned
> dependencies in `requirements.txt` and `seed_canonical = ${seed}`, re-execution
> produces bit-identical outputs.

| Field | Value |
|---|---|
| Version | `${version}` |
| Git snapshot | `${git_sha}` |
| Canonical regeneration timestamp (UTC) | `${timestamp}` |
| Author | ${author} ([ORCID ${orcid}](https://orcid.org/${orcid})) |
| License | ${license} |
| Bit-parity status | ✅ verified — re-execution under `seed_canonical = ${seed}` produces identical hashes |

---

## Purpose

This document is the **human-readable companion** to `output/experiment_provenance.json`. It records the SHA-256 chain that guarantees verifiable reproducibility of the Salabim discrete-event simulation that backs the published results.

Each hash is a **cryptographic proof** that, given identical source files and the canonical seed (`${seed}`) on Python ${python_version} with the pinned dependency set, execution is bit-deterministic across runs and across hardware. This *deterministic-by-design* property aligns the artifact with the FAIR principles (Wilkinson et al., 2016) and the ACM Artifact Review and Badging v1.1 guidelines.

```mermaid
flowchart LR
    A[Source files<br/>src/*.py] -->|SHA-256| B[experiment_provenance.json]
    C[Canonical seed = ${seed}] --> D[Salabim simulation]
    A --> D
    D -->|writes| E[output/results.json<br/>output/raw_replicas.jsonl]
    E -->|SHA-256| B
    B -->|template render| F[docs/hash-chain.md]
    G[Third-party verification] -->|pytest test_reproducibility| H{bit-parity OK?}
    H -->|✅| I[Reproducible]
    H -->|❌| J[Open issue]
```

---

## Canonical seed

```text
seed_canonical = ${seed}
```

Defined in `src/main.py`. Each replica `i` uses an isolated `random.Random(${seed} + i)` (no global state) to sample parameters from the operational range, and the same value `${seed} + i` is passed to `salabim.Environment(random_seed=...)` for the inner Monte-Carlo. Every execution under `seed_canonical = ${seed}` produces the same sequence of sampled parameters and the same discrete-event trajectory per replica.

---

## Source file hashes (SHA-256)

| File | SHA-256 |
|---|---|
${source_hash_rows}

---

## Output hashes (SHA-256)

| File | SHA-256 |
|---|---|
| `output/results.json` | `${results_sha}` |
| `output/raw_replicas.jsonl` | `${raw_sha}` |
| `output/experiment_provenance.json` | (auto-generated by `scripts/gen_provenance.py`) |
| `output/pareto_proof.json` | (regenerable via `scripts/pareto_proof.py`) |
| `output/saturated_pipeline.json` | (regenerable via `scripts/saturated_pipeline_plot.py`) |

---

## Pinned dependencies (resolved at provenance generation time)

| Package | Version |
|---|---|
${package_rows}

Full pin set in `requirements.txt`. Reproduction requires Python ${python_version} — use the included `Dockerfile` to guarantee the runtime.

---

## How to verify the chain (step-by-step)

### Step 1 — Verify source file hashes

```bash
shasum -a 256 src/__init__.py src/config.py src/simulation.py src/main.py src/report.py
```

Each hash must match the table above **exactly**. A 1-character divergence indicates the file was modified.

### Step 2 — Re-execute the canonical simulation

```bash
python -m venv .venv
.venv/bin/pip install -e ".[dev]"
.venv/bin/python -m src.main --replicates 300 --duration 1800 --workers 8
```

### Step 3 — Verify regenerated output hashes

```bash
shasum -a 256 output/results.json output/raw_replicas.jsonl
```

### Step 4 — Cross-validate via pytest

```bash
.venv/bin/python -m pytest tests/ -v
```

Expected: 53 tests pass in ~5.5 s. The test `test_reproducibility` explicitly verifies bit-parity of the p99 metric across two runs with the same seed.

> [!WARNING]
> If any of Steps 1–4 fails, do **not** ship results derived from the run. The chain is broken and must be re-established before downstream artifacts (figures, tables, paper) are considered valid.

---

## Reference Git snapshot

```text
commit ${git_sha}
```

This commit is the canonical truth point for version ${version}. To reproduce the exact snapshot that generated the hashes above:

```bash
git checkout ${git_sha}
```

Modifications after this commit do not invalidate the chain but produce different hashes. For academic citation, always pin to this commit (or the equivalent tagged release `v${version}`).

---

## Reference hardware (informative, not deterministic)

| Attribute | Value |
|---|---|
| Platform | `${hw_platform}` |
| Architecture | `${hw_machine}` |
| Logical CPUs | `${hw_cpus}` |
| Python implementation | `${hw_python_impl}` |

The hash chain is **hardware-independent**: Python ${python_version} with the pinned dependency set produces identical results on any compatible architecture (x86-64 Linux, arm64 macOS, etc.).

---

## Continuous self-validation

The chain must be regenerated and audited whenever:

1. Any file in `src/` is modified
2. Any canonical parameter in `config.py` changes
3. Any dependency in `requirements.txt` is upgraded
4. Before any tagged release on Zenodo / GitHub
5. Before any academic submission that cites this software

One-liner to regenerate:

```bash
python scripts/gen_provenance.py
python scripts/regen_hash_chain.py
```

---

## References

- ACM. (n.d.). *ACM Artifact Review and Badging v1.1*. <https://www.acm.org/publications/policies/artifact-review-and-badging-current>
- Citation File Format. (n.d.). *CFF specification v1.2*. <https://citation-file-format.github.io/>
- Wilkinson, M. D., Dumontier, M., Aalbersberg, I. J., Appleton, G., Axton, M., Baak, A., et al. (2016). 'The FAIR Guiding Principles for scientific data management and stewardship', *Scientific Data*, vol. 3, no. 1, p. 160018. <https://doi.org/10.1038/sdata.2016.18>
""")


def _render_source_rows(source_hashes: dict[str, str]) -> str:
    """Render the source-file hash table rows in deterministic order."""
    order = ["__init__.py", "config.py", "simulation.py", "main.py", "report.py"]
    rows = []
    for fn in order:
        if fn in source_hashes:
            rows.append(f"| `src/{fn}` | `{source_hashes[fn]}` |")
    return "\n".join(rows)


def _render_package_rows(packages: dict[str, str]) -> str:
    """Render the dependency-version table rows in alphabetical order."""
    rows = []
    for name in sorted(packages):
        rows.append(f"| {name} | `{packages[name]}` |")
    return "\n".join(rows)


def main() -> None:
    """Render `docs/hash-chain.md` from `output/experiment_provenance.json`."""
    if not _PROVENANCE.exists():
        print(
            f"ERROR: {_PROVENANCE} not found. "
            "Run `python scripts/gen_provenance.py` first.",
            file=sys.stderr,
        )
        sys.exit(1)

    with _PROVENANCE.open() as f:
        prov = json.load(f)

    rendered = _TEMPLATE.substitute(
        version=prov["version"],
        git_sha=prov["git_commit_sha"],
        timestamp=prov["timestamp_utc"],
        author=prov["author"],
        orcid=prov["orcid"],
        license=prov["license"],
        seed=prov["seed_canonical"],
        python_version=prov["hardware"]["python_version"],
        hw_platform=prov["hardware"]["platform"],
        hw_machine=prov["hardware"]["machine"],
        hw_cpus=prov["hardware"]["cpu_count"],
        hw_python_impl=prov["hardware"]["python_implementation"],
        results_sha=prov["results_sha256"],
        raw_sha=prov["raw_replicas_sha256"],
        source_hash_rows=_render_source_rows(prov["source_files_sha256"]),
        package_rows=_render_package_rows(prov["package_versions"]),
    )

    _OUTPUT.write_text(rendered)
    print(f"Wrote {_OUTPUT.relative_to(_ROOT)}")
    print(f"  source files: {len(prov['source_files_sha256'])}")
    print(f"  packages:     {len(prov['package_versions'])}")
    print(f"  version:      {prov['version']}")


if __name__ == "__main__":
    main()
